# -*- coding: utf-8 -*-

outpatientMap = {
        u'心臟內科' : 'CARDIO' ,
        u'免疫風濕科' : 'RHEUMATO',
 	u'風濕免疫科' : 'RHEUMATO',
        u'新陳代謝科' : 'METABOLISM_ENDOCRINO',
	u'新陳代謝內分泌科' : 'METABOLISM_ENDOCRINO', 
        u'神經內科' : 'NEUR' , 
	u'神經科' : 'NEUR' , 
        u'胃腸肝膽科' : 'GASTROENTERO' ,
	u'肝膽腸胃科' : 'GASTROENTERO' , 
        u'胸腔內科' : 'CHEST', 
        u'血液腫瘤科' : 'ONC',
        u'腎臟內科' : 'NCPHRO',
        u'一般內科' : 'MED', 
        u'心臟血管外科' : 'CADIR_THORACIC',
        u'泌尿外科' : 'URO',
	u'泌尿科' : 'URO',
        u'大腸直腸外科' : 'COLON_RECTAL',
        u'一般外科' : 'SURG',
        u'小兒外科' : 'SURG',
        u'神經外科' : 'NEURSURG',
        u'整形外科' : 'RECONSTRUCT',
        u'胸腔外科' : 'CHEST',
        u'手外科' : 'HAND_SURG',
        u'骨科' : 'ORTH',
        u'耳鼻喉科' : 'ENT',
        u'身心醫學科' : 'PSY',
	u'家庭醫學科' : 'HOME',
}

